modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Quests/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbquests"
version = "${version}"
displayName = "FTB Quests"
authors = "LatvianModder"
description = '''
Lets you easily create and play with quests
'''

[[dependencies.ftbquests]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.52,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1801.3.5-build.99,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "ftbteams"
mandatory = true
versionRange = "[1801.2.4-build.43,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "itemfilters"
mandatory = true
versionRange = "[1801.2.6-build.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "kubejs"
mandatory = false
versionRange = "[1801.4.0-build.245,)"
ordering = "AFTER"
side = "BOTH"