modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Teams/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbteams"
version = "${version}"
displayName = "FTB Teams"
authors = "LatvianModder"
description = '''
FTB Teams adds ability to create your own teams that can be used for quests etc.
'''

[[dependencies.ftbteams]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteams]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteams]]
modId = "architectury"
mandatory = true
versionRange = "[1.3.84,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteams]]
    modId="ftbguilibrary"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="CLIENT"
