name: Java CI - Build on Push

on:
  push:
    branches: [ main, dev, "1.**" ]
  workflow_dispatch:
    inputs:
      skip_maven_publish:
        description: 'Skip Maven publishing'
        required: true
        default: 'false'

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: FTBTeam/mods-meta/.github/workflows/standard-release.yml@main
    with:
      curse-publish-task: ""
      maven-snapshots: true
    secrets:
      ftb-maven-token: ${{ secrets.FTB_MAVEN_TOKEN }}
      saps-token: ${{ secrets.SAPS_TOKEN }}