name: Java CI - Build Release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-[a-z]+'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-[a-z]+\.[0-9]+'

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: FTBTeam/mods-meta/.github/workflows/standard-release.yml@main
    with:
      curse-publish-task: publishMods
      java-version: 21
    secrets:
      ftb-maven-token: ${{ secrets.FTB_MAVEN_TOKEN }}
      saps-token: ${{ secrets.SAPS_TOKEN }}
      curse-token: ${{ secrets.CURSEFORGE_KEY }}
